{"uuid":"b471e75b-87fc-4655-a799-db54ecb5cc06","name":"4. should throw an error for the factorial of a negative integer","historyId":"5ecf481037961f3043d136b23dc8296e:d41d8cd98f00b204e9800998ecf8427e","status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"jest"},{"name":"package","value":"functionsUnittests.mathFunctionsUnittest.calculateFactorial.test.ts"},{"name":"host","value":"pkrvmfkh1xnbeme"},{"name":"thread","value":"2"},{"name":"parentSuite","value":"calculateFactorial"}],"links":[],"start":1752001515133,"fullName":"functionsUnittests/mathFunctionsUnittest/calculateFactorial.test.ts#calculateFactorial 4. should throw an error for the factorial of a negative integer","testCaseId":"5ecf481037961f3043d136b23dc8296e","stop":1752001515136}